# For deployment to Google App Engine Standard (Not Flexible) Node.js Runtime
runtime: nodejs16

service: client

instance_class: F2

handlers:
  - url: /static
    static_dir: build/static
    secure: always

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$
    secure: always

  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always

env_variables:
  baseURL: "https://api.minipainters.net"
